import type {
  BoonEvent,
  ChatThread,
  Circle,
  Institution,
  LiveStream,
  Notification,
  Post,
  Therapist,
  User,
} from '@/utils/types';

const IMG = {
  amara: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=200&q=70',
  marcus: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=200&q=70',
  sofia: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&q=70',
  zara: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&q=70',
  david: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=70',
  jordan: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&q=70',
  maya: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=200&q=70',
  sam: 'https://images.unsplash.com/photo-1502685104226-ee32379fefbe?w=200&q=70',
  taylor: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&q=70',
  ravi: 'https://images.unsplash.com/photo-1488161628813-04466f872be2?w=200&q=70',
  ada: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=200&q=70',
  liam: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=200&q=70',
};

const POST_IMG = {
  hike: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=900&q=70',
  yoga: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=900&q=70',
  code: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=900&q=70',
  food: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=900&q=70',
  friends: 'https://images.unsplash.com/photo-1543807535-eceef0bc6599?w=900&q=70',
  book: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=900&q=70',
  art: 'https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=900&q=70',
  meditation: 'https://images.unsplash.com/photo-1474418397713-7ede21d49118?w=900&q=70',
};

const GALLERY = [
  'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=600&q=70',
  'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=600&q=70',
  'https://images.unsplash.com/photo-1543807535-eceef0bc6599?w=600&q=70',
  'https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=600&q=70',
  'https://images.unsplash.com/photo-1517457373958-b7bdd4587205?w=600&q=70',
  'https://images.unsplash.com/photo-1542038784456-1ea8e935640e?w=600&q=70',
];

export const ME_ID = 'me';

export const me: User = {
  id: ME_ID,
  name: 'LOGNETICS',
  handle: 'lognetics',
  avatar: undefined,
  bio: 'Here to network. Reader, photographer, writer.',
  location: 'Lagos, NG',
  interests: ['Reading', 'Photography', 'Writing', 'Fashion'],
  circles: ['neurodivergent', 'friendship', 'love', 'surrogacy', 'tech', 'fitness', 'creative'],
  status: 'Available',
  badges: ['Connector', 'Explorer'],
  online: true,
  plan: 'pro',
};

export const users: User[] = [
  {
    id: 'amara',
    name: 'Amara Johnson',
    avatar: IMG.amara,
    bio: 'Wellness coach & yoga instructor 🧘 I help people find balance and build meaningful connections.',
    location: 'Los Angeles, CA',
    interests: ['Yoga', 'Meditation', 'Fitness', 'Cooking'],
    circles: ['mindful', 'fitness'],
    status: 'Available',
    mutualConnections: 3,
    badges: ['Connector'],
    online: true,
    connected: true,
  },
  {
    id: 'marcus',
    name: 'Marcus Williams',
    avatar: IMG.marcus,
    bio: 'Software engineer by day, musician by night 🎸',
    location: 'Austin, TX',
    interests: ['Technology', 'Music', 'Hiking'],
    circles: ['tech'],
    status: 'Working',
    mutualConnections: 5,
    badges: ['Explorer'],
    online: true,
  },
  {
    id: 'sofia',
    name: 'Sofia Ramirez',
    avatar: IMG.sofia,
    bio: 'Graphic designer & coffee addict ☕ Passionate about art, travel, and authentic human connections.',
    location: 'Miami, FL',
    interests: ['Art', 'Design', 'Photography', 'Travel'],
    circles: ['creative', 'foodies'],
    status: 'Available',
    mutualConnections: 2,
    badges: ['Creative'],
    online: true,
  },
  {
    id: 'david',
    name: 'David Chen',
    avatar: IMG.david,
    bio: 'Entrepreneur & life-long learner 📚 Building cool things and connecting dots between ideas and people.',
    location: 'San Francisco, CA',
    interests: ['Business', 'Technology', 'Reading', 'Hiking'],
    circles: ['startup', 'tech'],
    status: 'Working',
    mutualConnections: 7,
    badges: ['Pioneer'],
    online: true,
  },
  {
    id: 'zara',
    name: 'Zara Ahmed',
    avatar: IMG.zara,
    bio: 'Therapist & mental health advocate 💜 Here to connect, listen, and grow together.',
    location: 'New York, NY',
    interests: ['Mental Health', 'Reading', 'Yoga'],
    circles: ['mindful', 'therapy'],
    status: 'Available',
    mutualConnections: 4,
    badges: ['Healer'],
    online: true,
  },
  {
    id: 'jordan',
    name: 'Jordan Lee',
    avatar: IMG.jordan,
    bio: 'Photographer chasing sunrise hikes 📸',
    location: 'Denver, CO',
    interests: ['Photography', 'Hiking', 'Travel'],
    circles: ['outdoor', 'creative'],
    status: 'Available',
    mutualConnections: 1,
    badges: ['Explorer'],
  },
  {
    id: 'maya',
    name: 'Maya Patel',
    avatar: IMG.maya,
    bio: 'Yoga instructor 🧘 community-builder, mindful living advocate.',
    location: 'Portland, OR',
    interests: ['Yoga', 'Meditation', 'Cooking'],
    circles: ['mindful', 'fitness'],
    status: 'Available',
    mutualConnections: 2,
    badges: ['Supporter'],
  },
  {
    id: 'sam',
    name: 'Sam Chen',
    avatar: IMG.sam,
    bio: 'Indie hacker & teacher 💻 building tiny tools, big communities.',
    location: 'Seattle, WA',
    interests: ['Coding', 'Teaching', 'Music'],
    circles: ['tech', 'creative'],
    status: 'Working',
    mutualConnections: 3,
    badges: ['Pioneer'],
  },
  {
    id: 'taylor',
    name: 'Taylor Kim',
    avatar: IMG.taylor,
    bio: 'Foodie + recipe creator. Always finding the next great ramen.',
    location: 'Chicago, IL',
    interests: ['Cooking', 'Food', 'Travel'],
    circles: ['foodies'],
    status: 'Available',
    mutualConnections: 2,
    badges: ['Creative'],
  },
  {
    id: 'ravi',
    name: 'Ravi Iyer',
    avatar: IMG.ravi,
    bio: 'ADHD founder. Coffee, code, conversations.',
    location: 'Toronto, ON',
    interests: ['Startup', 'ADHD', 'Reading'],
    circles: ['neurodivergent', 'startup'],
    status: 'Available',
    mutualConnections: 4,
    badges: ['Pioneer'],
    neurodivergent: true,
  },
  {
    id: 'ada',
    name: 'Ada Okafor',
    avatar: IMG.ada,
    bio: 'Writer / dyslexia advocate. Words my way.',
    location: 'Lagos, NG',
    interests: ['Writing', 'Reading', 'Advocacy'],
    circles: ['neurodivergent', 'creative'],
    status: 'Away',
    mutualConnections: 1,
    badges: ['Creative', 'Supporter'],
    neurodivergent: true,
  },
];

export const circles: Circle[] = [
  {
    id: 'sensory',
    name: 'Sensory Sensitive Circle',
    description: 'A gentle, quiet space for those with sensory processing differences.',
    members: 389,
    category: 'Neurodivergent',
    emoji: '🌿',
    consentTone: 'sensitive',
    rules: [
      'Be respectful and kind to all members',
      'No hate speech, harassment, or discrimination',
      'Keep discussions relevant to the community',
      "Respect others' privacy and boundaries",
      'Report harmful content to moderators',
    ],
    notice: 'Boonmate is a platform for connection. We do not moderate all content and are not responsible for interactions within this community.',
  },
  {
    id: 'neuro',
    name: 'Neurodivergent Community',
    description: 'A welcoming space for ADHD, autistic, dyslexic, and more.',
    members: 57,
    category: 'Neurodivergent',
    emoji: '🧠',
    consentTone: 'sensitive',
  },
  {
    id: 'friendship',
    name: 'Friendship Lab',
    description: 'For adults who want to make genuine, lasting friendships.',
    members: 46,
    category: 'Friendship',
    emoji: '🤝',
  },
  {
    id: 'gaming',
    name: 'Gaming Squad',
    description: 'Casual and competitive gamers welcome. Find your party.',
    members: 45,
    category: 'Tech',
    emoji: '🎮',
  },
  { id: 'tech', name: 'Tech Enthusiasts', description: 'For builders, coders, and tech lovers. Share projects.', members: 43, category: 'Tech', emoji: '💻' },
  { id: 'fitness', name: 'Fitness Crew', description: 'Stay active together! Share workouts, run clubs, and more.', members: 39, category: 'Fitness', emoji: '💪' },
  { id: 'foodies', name: 'Foodies United', description: 'Cook, eat, explore. Share recipes and discover spots.', members: 35, category: 'Food', emoji: '🍕' },
  { id: 'journey', name: 'Relationship Journey', description: 'Exploring healthy relationships, self-love, and growth.', members: 34, category: 'Love', emoji: '💞' },
  { id: 'startup', name: 'Startup Hub', description: 'Entrepreneurs and hustlers. Build, share, grow.', members: 33, category: 'Business', emoji: '🚀' },
  { id: 'love', name: 'Love & Connection', description: 'Deep conversations about love, dating, and partnership.', members: 32, category: 'Love', emoji: '❤️', premium: true },
  { id: 'therapy', name: 'Therapy Circle', description: 'A safe, supportive space to share your mental health journey.', members: 28, category: 'Therapy', emoji: '💜', consentTone: 'sensitive' },
  { id: 'outdoor', name: 'Outdoor Adventures', description: 'Hikers, campers, and nature enthusiasts. Plan together.', members: 24, category: 'Outdoors', emoji: '🌲' },
  { id: 'coach', name: 'Life Coaching Hub', description: 'Connect with coaches and coachees. Share goals.', members: 22, category: 'Education', emoji: '🌟' },
  { id: 'mindful', name: 'Mindful Living', description: 'Meditation, yoga, and wellness practices for a calmer life.', members: 20, category: 'Wellness', emoji: '🧘' },
  { id: 'coparent', name: 'Co-Parenting Circle', description: 'Support and resources for co-parents navigating shared life.', members: 19, category: 'Family', emoji: '👨‍👩‍👧' },
  { id: 'book', name: 'Book Club', description: 'Readers unite! Monthly picks, discussions, and more.', members: 19, category: 'Education', emoji: '📚' },
  { id: 'future', name: 'Future Parents Club', description: "For those who know they want kids someday — and want a tribe.", members: 17, category: 'Family', emoji: '🍼' },
  {
    id: 'surrogacy',
    name: 'Surrogacy Support',
    description: 'A warm community for surrogates, intended parents, and allies — informational only.',
    members: 13,
    category: 'Family',
    emoji: '🤍',
    consentTone: 'surrogacy',
    rules: [
      'Share experiences respectfully and compassionately',
      'No solicitation of surrogates or intended parents',
      'Do not share personal medical details publicly',
      'Always consult verified institutions and legal counsel',
      'Be sensitive to all family-building paths',
    ],
    notice:
      "IMPORTANT: Boonmate does not facilitate surrogacy arrangements. All surrogacy should be arranged ONLY through licensed fertility clinics and legal professionals. This community is for emotional support only. Boonmate is not liable for any arrangements made.",
  },
  {
    id: 'creative',
    name: 'Creative Studio',
    description: 'Designers, artists, writers — share craft and feedback.',
    members: 28,
    category: 'Creatives',
    emoji: '🎨',
  },
  // Neurodiversity hub circles
  { id: 'autism', name: 'Autism Support Circle', description: 'A calm, structured space for autistic individuals and allies.', members: 847, category: 'Neurodivergent', emoji: '💙', consentTone: 'sensitive' },
  { id: 'adhd', name: 'ADHD Circle', description: 'Energy, creativity, and focus strategies for ADHDers.', members: 1203, category: 'Neurodivergent', emoji: '⚡', consentTone: 'sensitive' },
  { id: 'dyslexia', name: 'Dyslexia Creatives', description: 'Celebrating the creative power of dyslexic minds.', members: 432, category: 'Neurodivergent', emoji: '🎨', consentTone: 'sensitive' },
  { id: 'neurodiverse', name: 'Neurodiverse Community', description: 'For anyone who thinks, feels, or experiences the world differently.', members: 2156, category: 'Neurodivergent', emoji: '🧠', consentTone: 'sensitive' },
];

export const CIRCLE_CATEGORIES = [
  'All', 'Tech', 'Fitness', 'Faith', 'Creatives', 'Outdoors', 'Food', 'Wellness', 'Business', 'Education',
  'Social', 'Neurodivergent', 'Therapy', 'Friendship', 'Love', 'Family',
];

const now = Date.now();
const daysAgo = (n: number) => new Date(now - n * 24 * 60 * 60 * 1000).toISOString();
const minsAgo = (n: number) => new Date(now - n * 60 * 1000).toISOString();
const hoursAgo = (n: number) => new Date(now - n * 60 * 60 * 1000).toISOString();

export const posts: Post[] = [
  {
    id: 'p_me_1',
    authorId: ME_ID,
    authorName: me.name,
    circleId: 'surrogacy',
    circleName: 'Surrogacy Support',
    createdAt: hoursAgo(1),
    text: 'Hello world',
    likes: 0,
    comments: 0,
  },
  {
    id: 'p1',
    authorId: 'amara',
    authorName: 'Amara Johnson',
    authorAvatar: IMG.amara,
    circleId: 'mindful',
    circleName: 'Mindful Living',
    createdAt: daysAgo(16),
    text: "Reminder: You don't have to have it all figured out to deserve connection. Show up as you are today 💜 #MindfulLiving #YouAreEnough",
    likes: 47,
    comments: 12,
    liked: true,
  },
  {
    id: 'p2',
    authorId: 'marcus',
    authorName: 'Marcus Williams',
    authorAvatar: IMG.marcus,
    circleId: 'tech',
    circleName: 'Tech Enthusiasts',
    createdAt: daysAgo(16),
    text: 'Just shipped my side project! 🚀 Three months of late nights, coffee, and YouTube tutorials. Looking for beta testers from the Tech Enthusiasts circle — DM me!',
    likes: 38,
    comments: 15,
    image: POST_IMG.code,
  },
  {
    id: 'p3',
    authorId: 'sofia',
    authorName: 'Sofia Ramirez',
    authorAvatar: IMG.sofia,
    createdAt: daysAgo(16),
    text: "PSA: Being single as an adult doesn't mean you're broken. I used to think something was wrong with me. Boonmate helped me realize I just hadn't found MY people yet 🌸 This community changed everything.",
    likes: 93,
    comments: 31,
  },
  {
    id: 'p4',
    authorId: 'jordan',
    authorName: 'Jordan Lee',
    authorAvatar: IMG.jordan,
    circleId: 'outdoor',
    circleName: 'Outdoor Adventures',
    createdAt: daysAgo(16),
    text: "This morning's sunrise hike was incredible! There's nothing like sharing these moments with amazing people. Who's joining the next one? 🌄",
    image: POST_IMG.hike,
    likes: 23,
    comments: 7,
  },
  {
    id: 'p5',
    authorId: 'maya',
    authorName: 'Maya Patel',
    authorAvatar: IMG.maya,
    circleId: 'mindful',
    circleName: 'Mindful Living',
    createdAt: daysAgo(16),
    text: 'Reminder: Yoga in the Park this Saturday at 7:30 AM! All levels welcome. Bring your mat and good energy. 🧘',
    image: POST_IMG.yoga,
    likes: 56,
    comments: 18,
  },
  {
    id: 'p6',
    authorId: 'sam',
    authorName: 'Sam Chen',
    authorAvatar: IMG.sam,
    circleId: 'tech',
    circleName: 'Tech Enthusiasts',
    createdAt: daysAgo(16),
    text: 'Built a mini weather app in our Code & Create session today! So cool to see everyone\'s projects come together. Community learning hits different 💻✨',
    image: POST_IMG.code,
    likes: 31,
    comments: 9,
  },
  {
    id: 'p7',
    authorId: 'taylor',
    authorName: 'Taylor Kim',
    authorAvatar: IMG.taylor,
    circleId: 'foodies',
    circleName: 'Foodies United',
    createdAt: daysAgo(16),
    text: 'Tried the new ramen spot downtown with folks from the Foodies circle. 10/10 would recommend the spicy miso! 🍜',
    image: POST_IMG.food,
    likes: 42,
    comments: 11,
  },
  {
    id: 'p8',
    authorId: 'david',
    authorName: 'David Chen',
    authorAvatar: IMG.david,
    circleId: 'startup',
    circleName: 'Startup Hub',
    createdAt: daysAgo(15),
    text: "Hot take: The best business decisions come from real human conversations, not just data. Met two co-founders in this circle last month. Now we're building together.",
    likes: 62,
    comments: 22,
  },
  {
    id: 'p9',
    authorId: 'zara',
    authorName: 'Zara Ahmed',
    authorAvatar: IMG.zara,
    circleId: 'therapy',
    circleName: 'Therapy Circle',
    createdAt: daysAgo(14),
    text: 'Small reminder for today: rest is not a reward. It is a requirement. 💜',
    likes: 88,
    comments: 14,
  },
  {
    id: 'p10',
    authorId: 'ravi',
    authorName: 'Ravi Iyer',
    authorAvatar: IMG.ravi,
    circleId: 'adhd',
    circleName: 'ADHD Circle',
    createdAt: daysAgo(12),
    text: 'ADHD tip that changed my life: body doubling. Just having someone else "exist" near me while I work makes everything 10x easier. Anyone else?',
    likes: 134,
    comments: 41,
  },
  {
    id: 'p11',
    authorId: 'ada',
    authorName: 'Ada Okafor',
    authorAvatar: IMG.ada,
    circleId: 'dyslexia',
    circleName: 'Dyslexia Creatives',
    createdAt: daysAgo(10),
    text: 'Dyslexia gave me the gift of seeing connections others miss. Wouldn\'t trade my brain for anything. 🎨',
    image: POST_IMG.art,
    likes: 92,
    comments: 19,
  },
  {
    id: 'p12',
    authorId: 'amara',
    authorName: 'Amara Johnson',
    authorAvatar: IMG.amara,
    circleId: 'mindful',
    circleName: 'Mindful Living',
    createdAt: daysAgo(9),
    text: '"You can\'t pour from an empty cup" — but you also can\'t fill your own cup from someone else\'s. Build your community. Refill each other.',
    image: POST_IMG.meditation,
    likes: 73,
    comments: 16,
  },
  {
    id: 'p13',
    authorId: 'sofia',
    authorName: 'Sofia Ramirez',
    authorAvatar: IMG.sofia,
    circleId: 'creative',
    circleName: 'Creative Studio',
    createdAt: daysAgo(7),
    text: 'Calling all designers — what does "community" look like to you in a single image? Tag me, I\'m building a moodboard.',
    image: POST_IMG.art,
    likes: 51,
    comments: 24,
  },
  {
    id: 'p14',
    authorId: 'marcus',
    authorName: 'Marcus Williams',
    authorAvatar: IMG.marcus,
    createdAt: daysAgo(3),
    text: 'Open call: anyone in Austin want to start a Sunday coffee + walk meetup? No agenda. Just real talk. ☕',
    likes: 29,
    comments: 13,
  },
];

export const chats: ChatThread[] = [
  {
    id: 'c_amara',
    withUserId: 'amara',
    preview: 'Riverside Park by the fountain 🧘',
    at: minsAgo(82),
    messages: [
      { id: 'm1', fromId: 'amara', text: 'Hey! I saw you joined the Mindful Living circle 🌿 Welcome!', at: minsAgo(118) },
      { id: 'm2', fromId: ME_ID, text: "Thank you Amara! I've been looking for a wellness community for a while 😊", at: minsAgo(116) },
      { id: 'm3', fromId: 'amara', text: 'We do sunrise yoga every Saturday in the park. You should join us!', at: minsAgo(115) },
      { id: 'm4', fromId: ME_ID, text: 'That sounds amazing! Where exactly do you meet?', at: minsAgo(114) },
      { id: 'm5', fromId: 'amara', text: 'Riverside Park by the fountain 🧘', at: minsAgo(82) },
    ],
  },
  {
    id: 'c_marcus',
    withUserId: 'marcus',
    preview: 'Definitely! We should pair up on something',
    at: daysAgo(1),
    unread: 1,
    messages: [
      { id: 'm1', fromId: 'marcus', text: 'Loved your last post on the tech circle 🔥', at: daysAgo(1) },
      { id: 'm2', fromId: 'marcus', text: 'Definitely! We should pair up on something', at: daysAgo(1) },
    ],
  },
  {
    id: 'c_sofia',
    withUserId: 'sofia',
    preview: "Perfect! I'll tag you when we plan the next one 🥾",
    at: daysAgo(4),
    messages: [
      { id: 'm1', fromId: 'sofia', text: 'Hey! Joining the next hangout?', at: daysAgo(4) },
      { id: 'm2', fromId: ME_ID, text: 'Yes please!', at: daysAgo(4) },
      { id: 'm3', fromId: 'sofia', text: "Perfect! I'll tag you when we plan the next one 🥾", at: daysAgo(4) },
    ],
  },
  {
    id: 'c_zara',
    withUserId: 'zara',
    preview: 'I run a small support group on Sunday evenings…',
    at: daysAgo(6),
    unread: 2,
    messages: [
      { id: 'm1', fromId: 'zara', text: 'I saw your post on the therapy circle 💜', at: daysAgo(6) },
      { id: 'm2', fromId: 'zara', text: 'I run a small support group on Sunday evenings…', at: daysAgo(6) },
    ],
  },
];

export const events: BoonEvent[] = [
  { id: 'e1', title: 'Weekend Hike: Sunset Trail', category: 'Outdoor', emoji: '🌲', date: 'May 03', time: '4:00 PM', location: 'Sunset Trail Park', going: 15, attending: true, past: true, description: 'A relaxed hike with bay views. Bring water!' },
  { id: 'e2', title: 'Morning Coffee Meetup', category: 'Hangout', emoji: '☕', date: 'May 01', time: '9:00 AM', location: 'Central Perk Café', going: 8, past: true },
  { id: 'e3', title: 'Board Game Night', category: 'Gaming', emoji: '🎲', date: 'May 02', time: '7:00 PM', location: 'The Game Room', going: 12, past: true },
  { id: 'e4', title: 'Weekend Hike: Sunset Trail', category: 'Outdoor', emoji: '🌲', date: 'May 03', time: '4:00 PM', location: 'Sunset Trail Park', going: 15, past: true },
  { id: 'e5', title: 'Code & Create Workshop', category: 'Workshop', emoji: '🛠️', date: 'May 05', time: '6:00 PM', location: 'Innovation Hub, Floor 2', going: 22, past: true },
  { id: 'e6', title: 'Friendship Speed-Networking', category: 'Meetup', emoji: '👋', date: 'May 07', time: '6:30 PM', location: 'The Common House', going: 24, past: true },
  { id: 'e7', title: 'Co-Parenting Support Meetup', category: 'Support Group', emoji: '💙', date: 'May 09', time: '10:00 AM', location: 'Family Resource Center', going: 11, past: true },
  { id: 'e8', title: 'Women in Tech Brunch', category: 'Networking', emoji: '🌐', date: 'May 10', time: '11:00 AM', location: 'The Innovation Cafe', going: 18, past: true },
  { id: 'e9', title: 'Mindfulness & Movement Morning', category: 'Wellness', emoji: '🧘', date: 'May 11', time: '8:00 AM', location: 'Riverside Park Pavilion', going: 14, past: true },
];

export const notifications: Notification[] = [
  { id: 'n1', kind: 'connect', title: 'Sofia wants to connect', body: 'You have 2 mutual circles', at: minsAgo(8), read: false },
  { id: 'n2', kind: 'event', title: 'Sunrise Yoga starts in 30 min', body: 'Riverside Park Pavilion', at: minsAgo(45), read: false },
  { id: 'n3', kind: 'message', title: 'Zara sent you a message', body: 'I run a small support group on Sunday evenings…', at: hoursAgo(2), read: true },
];

export const therapists: Therapist[] = [
  {
    id: 't1', name: 'Dr. Lena Park', role: 'Licensed Clinical Psychologist',
    bio: 'Anxiety, ADHD, and identity. Warm, structured sessions.',
    avatar: IMG.zara, specialties: ['Anxiety', 'ADHD', 'Identity'],
    location: 'Brooklyn, NY', contact: { email: 'lena@demo.boonmate.app' },
    availability: 'Available', rating: 4.9, verified: true,
  },
  {
    id: 't2', name: 'Coach Marcus Hale', role: 'Certified Life Coach',
    bio: 'Career transitions, confidence, and friendship.',
    avatar: IMG.marcus, specialties: ['Career', 'Confidence', 'Friendship'],
    location: 'Austin, TX', contact: { phone: '+1 (555) 010-0102' },
    availability: 'Available', rating: 4.7, verified: true,
  },
  {
    id: 't3', name: 'Dr. Amaka Chukwu', role: 'Family Therapist',
    bio: 'Co-parenting, relationships, family systems.',
    avatar: IMG.ada, specialties: ['Co-parenting', 'Family', 'Relationships'],
    location: 'Atlanta, GA', contact: { email: 'amaka@demo.boonmate.app' },
    availability: 'Away', rating: 4.8, verified: true,
  },
  {
    id: 't4', name: 'Sara Olsen, LMFT', role: 'Marriage & Family Therapist',
    bio: 'Couples and individual work. EFT-informed.',
    avatar: IMG.sofia, specialties: ['Couples', 'Communication'],
    location: 'Minneapolis, MN', contact: { email: 'sara@demo.boonmate.app' },
    availability: 'Available', rating: 4.9, verified: true,
  },
  {
    id: 't5', name: 'Coach Ravi Iyer', role: 'ADHD & Productivity Coach',
    bio: 'Neurodivergent-friendly. Body doubling, exec function.',
    avatar: IMG.ravi, specialties: ['ADHD', 'Executive Function', 'Productivity'],
    location: 'Toronto, ON', contact: { demoUrl: 'https://demo.boonmate.app/coach/ravi' },
    availability: 'Available', rating: 4.8, verified: true,
  },
  {
    id: 't6', name: 'Dr. Jamal Brooks', role: 'Trauma-Informed Therapist',
    bio: 'CPTSD, identity, men\'s mental health.',
    avatar: IMG.david, specialties: ['Trauma', 'Identity', "Men's Mental Health"],
    location: 'Chicago, IL', contact: { email: 'jamal@demo.boonmate.app' },
    availability: 'Booked', rating: 4.9, verified: true,
  },
];

export const institutions: Institution[] = [
  {
    id: 'i1', name: 'Pacific Fertility Institute',
    location: 'San Francisco, CA',
    description: 'Licensed fertility clinic offering IVF, surrogacy coordination via legal partners.',
    contact: { phone: '+1 (555) 011-0100', email: 'info@demo.boonmate.app', website: 'https://demo.boonmate.app/pfi' },
  },
  {
    id: 'i2', name: 'Sunrise Reproductive Medicine',
    location: 'Austin, TX',
    description: 'Family-building specialists. Counseling, IVF, donor and gestational carrier programs.',
    contact: { phone: '+1 (555) 011-0101', website: 'https://demo.boonmate.app/srm' },
  },
  {
    id: 'i3', name: 'New Horizons Surrogacy Law Group',
    location: 'New York, NY',
    description: 'Legal counsel for intended parents and surrogates. We do not match — we represent.',
    contact: { email: 'contact@demo.boonmate.app', website: 'https://demo.boonmate.app/nhslg' },
  },
];

export const growthHubItems = [
  { id: 'g1', emoji: '🌱', title: 'Make Friends as an Adult', body: 'Three rituals that make grown-up friendship easier than it looks.' },
  { id: 'g2', emoji: '🧘', title: 'Tiny Wellness Reset', body: 'A five-minute reset for when the day already feels heavy.' },
  { id: 'g3', emoji: '💜', title: 'Healthy Boundaries 101', body: 'Boundaries aren\'t walls. They\'re bridges with rules.' },
  { id: 'g4', emoji: '🚀', title: 'Personal Growth Sprint', body: 'A 14-day, one-prompt-a-day journal for becoming who you want to be.' },
  { id: 'g5', emoji: '🤝', title: 'Better Conversations', body: 'How to ask the second question — and why it matters.' },
];

export const liveStreams: LiveStream[] = [
  {
    id: 'l1',
    hostId: 'amara',
    hostName: 'Amara Johnson',
    hostAvatar: IMG.amara,
    title: 'Sunrise yoga, riverside — join me 🧘',
    thumbnail: POST_IMG.yoga,
    viewers: 142,
    startedAt: minsAgo(8),
    audience: 'public',
  },
  {
    id: 'l2',
    hostId: 'marcus',
    hostName: 'Marcus Williams',
    hostAvatar: IMG.marcus,
    title: 'Live coding: shipping the side project today',
    thumbnail: POST_IMG.code,
    viewers: 87,
    startedAt: minsAgo(22),
    audience: 'public',
    circleId: 'tech',
  },
  {
    id: 'l3',
    hostId: 'sofia',
    hostName: 'Sofia Ramirez',
    hostAvatar: IMG.sofia,
    title: 'Studio session — ask me anything about design',
    thumbnail: POST_IMG.art,
    viewers: 34,
    startedAt: minsAgo(3),
    audience: 'public',
  },
  {
    id: 'l4',
    hostId: 'zara',
    hostName: 'Zara Ahmed',
    hostAvatar: IMG.zara,
    title: 'Mindful evening reset — bring tea ☕',
    thumbnail: POST_IMG.meditation,
    viewers: 211,
    startedAt: minsAgo(45),
    audience: 'public',
  },
  {
    id: 'l5',
    hostId: 'jordan',
    hostName: 'Jordan Lee',
    hostAvatar: IMG.jordan,
    title: 'Hiking up Cathedral Rock 🏔️',
    thumbnail: POST_IMG.hike,
    viewers: 58,
    startedAt: minsAgo(14),
    audience: 'public',
  },
];

export const liveStarterComments = [
  { name: 'David Chen', text: 'Just joined! ✨', avatar: IMG.david },
  { name: 'Sam Chen', text: 'Love this 🔥', avatar: IMG.sam },
  { name: 'Taylor Kim', text: 'How long are you going to be live?', avatar: IMG.taylor },
  { name: 'Maya Patel', text: '👏👏👏', avatar: IMG.maya },
  { name: 'Ravi Iyer', text: 'Tuning in for the next 20 min', avatar: IMG.ravi },
  { name: 'Ada Okafor', text: 'You\'re doing amazing 💜', avatar: IMG.ada },
];

export const gallery = GALLERY;
export const dailyInsights = [
  '🌱 Growth tip: Authentic connections start with vulnerability. Share something real today.',
  '💜 Reminder: Rest is not a reward. It is a requirement.',
  '🚀 Tiny step: Send one message to someone you\'ve been thinking about. That\'s the whole job today.',
  '✨ The quality of your community shapes the quality of your decisions.',
];

export function suggestedAIPeople(): User[] {
  return users.filter((u) => !u.connected).slice(0, 3);
}

export function aiTopicReplies(topic: string): string[] {
  return [
    `Let\'s talk about ${topic.toLowerCase()}. Where would you like to start — your experience so far, or what you wish were different?`,
    'Here are three small ideas you can try this week, in 5 minutes or less. We can pick one together.',
    'What you\'re describing is more common than you think. I\'m here, no judgment — take your time.',
  ];
}
